Agoric/instagoric

- bases/shared/instagoric-server/server.js
refs https://github.com/Agoric/agoric-sdk/issues/4654#issuecomment-1217441170
cc @samsiegart
> feat(instagoric-server): add SMART_WALLET option to faucet

- bases/primaryvalidator/kustomization.yaml
- bases/validators/kustomization.yaml
Increase memory for instagoric validator nodes.
> Increase memory of validators

- bases/shared/entrypoint.sh
Don't hang forever, just until the sleep is killed or `/state/hang` is removed.
> fix(entrypoint): make `/state/hang` interruptible

- bases/shared/entrypoint.sh
> feat: clear TMPDIR on restart

- bases/node/node.yaml
Relevant discussion: https://agoricopco.slack.com/archives/C039QGBN0JF/p1718832108062769
> Reduce ephemeral-storage

- bases/seed/kustomization.yaml
- bases/shared/entrypoint.sh
* Use latest mainfork snapshot
* remove vatstore metrics which we haven't used much and add extra load on sqllite database.
> Update mainfork with post-u15 state

- bases/shared/instagoric-server/server.js
fixes https://github.com/Agoric/dapp-inter/issues/348
> fix: use testnet-compatible dapp-inter link

- bases/shared/instagoric-server/server.js
This PR adds a link to the deployment logs
> Grafana Deployment Link

- bases/shared/instagoric-server/package.json
- bases/shared/instagoric-server/server.js
- bases/shared/instagoric-server/yarn.lock
Issue: [Fix emerynet's faucet's flakyness](https://github.com/orgs/Agoric/projects/19/views/1?filterQuery=assignee%3Ausmanmani1122&pane=issue&itemId=75006299)
This PR fixes the flakiness of faucet. The reason for the flakiness is usage of `block` broadcast mode for the transactions. This mode waits for the transaction to be included in a block before returning a response which can timeout in some cases. More details can be found in the linked issue.
The flow is now updated to use `sync` broadcast mode. The sync mode only waits for [CheckTx](https://docs.cosmos.network/main/learn/advanced/baseapp#checktx-state-updates) validation (without waitng for [DeliverTx](https://docs.cosmos.network/v0.47/learn/beginner/tx-lifecycle#delivertx)). The user is then navigated to a status page which polls …
> Fix emerynet's faucet's flakyness

- bases/shared/entrypoint.sh
This PR replaces the namespace attribute in otel config with actual value
> Namespace in datadog tags

- bases/shared/instagoric-server/server.js
This PR fixes the Emerynet tests by adding delegate and client commands in instagoric faucet server. 
We ideally should update the test to pass updated commands but for quick mitigation, updated the instagoric-server.
> Fix(commands): 'client and delegate' Command Re-Added;

- bases/shared/instagoric-server/server.js
Logs/Dashboard link is changed to `monitor.agoric.net`
> chore: Change Logs & Dashboard URL to monitor.agoric.net

- bases/shared/instagoric-server/README.md
Updating `bases/shared/instagoric-server/README.md` with instructions for starting the dev server.
> docs: starting the dev server

- bases/node/node.yaml
- bases/shared/entrypoint.sh
This updates the mainfork height and add OTEL reporting endpoint environmental variable
**Should be merged after [this](https://github.com/Agoric/instagoric-private/pull/92) PR**
> Enable context slogger

- bases/shared/scripts/main.sh
- bases/shared/scripts/source.sh
This PR enables contextual slogging supported in upgrade 18
> chore: Upgrade 18

- bases/shared/scripts/main.sh
- bases/shared/scripts/source.sh
This PR enables bootstrap config patch support
> feat: Bootstrap config patch support

- bases/shared/instagoric-server/server.js
- overlays/local/kustomization.yaml
This PR fixes the local cluster deployment
> fix: Local deployment

- bases/shared/instagoric-server/server.js
Currently we use `agd query bank total` to show all the denoms in supply for the custom denoms list in the faucet. But the denoms not held by the whale cannot be transferred so users face errors for those denoms
This PR only shows denoms held by the whale by using `agd query bank balances` instead
One issue here could be that the difference in whales balance of different pods can also raise some error (custom denoms list fetched by one pod but transaction triggered by another pod) but that is a rare case
> fix(faucet): Only denoms held by whale should be visible in custom denoms list

- bases/shared/instagoric-server/causeway.js
This PR adds a redirection handler which will point to the logs of a run ID with appropriate filters applied
> feat: Logs handler for a run ID

- bases/node/node.yaml
- bases/shared/instagoric-server/app.js
- bases/shared/instagoric-server/server.js
> feat: initial claim-ymax-endpoint
