- bases/node/node.yaml
- bases/primaryvalidator/service.yaml
- bases/seed/service.yaml
- bases/shared/entrypoint.sh
closes: #3
closes: Agoric/instagoric-private#2
- remove unconditional call to `hang` from `entrypoint.sh` because it would allow the executed program to exit without k8s noticing the fact (which prevented automatic restart)
- the above change allows us to eschew liveness checks (since the startup probe might cause pod death due to unanticipated but normal delays in starting a node), at least until we have a clear signal of when the node is doing useful work
- add readiness check developed with @raphdev to ensure traffic is not routed to nodes that are not caught-up
- the above change alone causes a deadlock when trying to start the chain, so solve that by adding `publishNotReadyAddresses: true` to internal services used only for coordination during startup
> feat(node): readiness checks for nodes

- bases/shared/entrypoint.sh
When partners add new contracts, we would like to see how they are behaving in terms of CPU/Memory usage. Contracts run inside Vats, and we want to get these metrics from Vat processes. 
I tried getting process-level metrics by enabling them in `private-bases/telemetry/otel-config.yaml` but Otel or DD were not able to deliver all the labels to allow us to view per process metrics, and instead all xsnap-worker process instances had their metrics aggregated.
The alternative solution I am going with is to add `prometheus-process-exporter` and run it to collect process level metrics. There is a separate PR that configured DD to receive these metrics.
This PR does the following.
1. Install prometheus-process-exporter
2. Create a config of the following format.
```
process_names:
- name: "v1" …
```
> Add prometheus-process-exporter

- scripts/store-stats/package.json
- scripts/store-stats/store-stats.js
This tool is designed to periodically gather statistics from a SwingStore SQLite database, specifically counting rows related to Vat storage. It then exposes these metrics in a format suitable for scraping by a Prometheus instance.
Usage: `node store-stats.js swingstore.sqlite`
Metrics can be fetched by `curl http://localhost:9184/metrics` to get the following.
```
target_info{service_name="unknown_service:node",telemetry_sdk_language="nodejs",telemetry_sdk_name="opentelemetry",telemetry_sdk_version="1.17.0"} 1
vatstore_rows{vatId="v1"} 325
vatstore_rows{vatId="v2"} 216
vatstore_rows{vatId="v8"} 64
vatstore_rows{vatId="v7"} 477
vatstore_rows{vatId="v6"} 333
vatstore_rows{vatId="v11"} 2430
vatstore_rows{vatId="v9"} 585721
vatstore_rows{vatId="v3"} 9
vatstore_rows{vatId="v13"} 193 …
```
> Store stats exporter tool

- bases/node/node.yaml
- bases/shared/entrypoint.sh
- Make liveness check robust against timeouts in `agd status`
- Set `external_address` correctly so that there is better network connectivity between validators
- Lowercase function-local variables to avoid overwriting uppercase constant variables
> fix: improved liveness check and network connectivity

- bases/shared/entrypoint.sh
Add node(agd) process metrics included in the config for process-metrics exporter.
Fix fork setup code to check for right file existence to skip the download.
Remove --x-crisis-skip-assert-invariants that we don't need at this stage for running fork.
> Add node metrics, fix old state check, fix fork node params

- bases/node/node.yaml
- bases/shared/entrypoint.sh
- Remove tmpfs
- Add agd process stats
- Increase the number of vats to monitor
**Details on tmpfs fix:**
Fix the /tmp ramdisk issue causing crashes in Instagoric testnets, particularly noticeable post-upgrade13 on emerynet. The state-sync fix, while enabling more snapshots, inadvertently led to excessive RAM usage due to the following:
- Our validators' /tmp was set to a ramdisk-based tmpfs filesystem, directly consuming RAM for each byte written.
- Creating a state-sync snapshot involved writing 20-50 GB to /tmp/.
- This usage triggered the OOM Killer, as it counts against RAM limits but isn't reflected in most of our monitoring metrics.
- The RAM consumed by tmpfs wasn't attributed to any specific process.
- Consequently, the validator pod was terminated by the OOM Killer due to high …
> Remove ramdisk mount from /tmp

- README.md
- bases/primaryvalidator/kustomization.yaml
- bases/rpcnodes/service.yaml
- bases/shared/instagoric-server/package.json
- bases/shared/instagoric-server/server.js
- bases/shared/serviceaccount.yaml
- kustomization.yaml
- overlays/ag0/kustomization.yaml
- overlays/follower/kustomization.yaml
- overlays/fork/kustomization.yaml
- overlays/local/kustomization.yaml
- overlays/testnet/kustomization.yaml
- scripts/kagd.sh
Don't explicitly pass `-n instagoric`... let the user set proper config like `kubectl config set-context --current --namespace=<ns>`.
This allows for multiple Instagoric namespaces per cluster.
> feat: make instagoric independent of namespace name

- bases/shared/entrypoint.sh
- bases/shared/instagoric-server/server.js
- Properly display Docker image name, not just a hardcoded `ghcr.io/agoric/agoric-sdk` name with the correct tag.
- Copy the `$BOOTSTRAP_CONFIG` from `/config/network/$(basename "$BOOTSTRAP_CONFIG")` if it exists.  This allows overriding the VM configuration with just a merged `network-config` configMapGenerator`.
> Axlenet enablers

- bases/follower/kustomization.yaml
- bases/primaryvalidator/kustomization.yaml
- bases/seed/kustomization.yaml
- bases/shared/entrypoint.sh
- bases/validators/kustomization.yaml
- overlays/follower/kustomization.yaml
We have manually updated the disk space of most clusters so the disk update here is needed for future deployment.
To expose RPC ports, we need to add rpcnodes service in the followers.
> Fix disk sizes and add rpcnodes in follower

- bases/shared/entrypoint.sh
We already have process metrics in Datadog through K8 + datadog magic integration but we were not able to see them before because we didn't know how to expose them in datadog.
https://us3.datadoghq.com/process?selectedTopGraph=timeseries
The above URL shows the processes-related metrics. We have added a graph in the dashboard that uses Processes but the metrics are only retained for 36 hours. There is a way to increase that retention by creating custom metrics based on Process metrics that we should try.
After this change is deployed, then some of the memory/cpu graphs will be turned off in the testnet dashboards. We will also lose the total Vats graph because that depends on these metrics being removed. Later we should find a way to show the running Vat process number using custom …
> Remove process metrics reporting

- bases/shared/serviceaccount.yaml
As described in chat:
> The specification in `serviceaccount.yaml` narrowed the `ClusterRoleBinding` to only work with the namespace that was currently being configured.  In the past, this namespace was always `instagoric`, but now, the namespace was the most recent configured one (`orchnet` as of this weekend).  In doing so, it denied access to the other namespaces in the same cluster.
> fix(serviceaccount): make local `RoleBinding`, not `ClusterRoleBinding`

- bases/shared/entrypoint.sh
- bases/shared/instagoric-server/yarn.lock
Fix: Updated the mainfork snapshot height which is currently already deployed on ollinet.
Fix: instagoric server is not working because of outdated yarn.log.
> update mainfork snapshot (post u16)

- bases/shared/instagoric-server/server.js
We have enabled logs Explore dashboard on grafana (in https://github.com/Agoric/instagoric-private/pull/66)
This PR just points the logs url to Explore page with required filters.
_Please ignore the formatting change, the file was formatted on save_.
> Replace Grafana Logs Url from Dashboard to Explore;

- bases/shared/instagoric-server/server.js
- bases/shared/instagoric-server/yarn.lock
https://github.com/user-attachments/assets/7a392a93-ec8d-43bb-a6ca-8541ec551972
**Background/Problem:** In our faucet app, we send funds to an address and also fund the provision pool. There are only two options `send IST` and `send BLD/IBC` with a hardcoded amount in code. So we can't send custom denoms if needed.
**Solution:** This PR shows a list of denoms (fetched from chain) and show them as a third custom option. Minor refactoring at server is also done (Pre-defined commands types, PROVISIONING_POOL_ADDR is picked from server rather than client, common functions etc..). The clip attached above can further explain the use-case.
> Feat(Instagoric): Custom Denoms Support through Faucet

- bases/node/node.yaml
- bases/shared/entrypoint.sh
This PR enables metrics reporting to GCP. Need a higher version of otel to enable the required exporter.
> Enable otel metrics reporting to GCP

- bases/shared/cron.sh
- bases/shared/entrypoint.sh
- bases/shared/kustomization.yaml
- bases/shared/restart-pods.sh
- bases/shared/serviceaccount.yaml
This PR enables pods periodic restarts (every 6 hours). The motivation for this change is to keep the log files size in check. Restarting the pods will start a new log file and will remove the old log file (after backup) which will keep the persistent volume usage low.
The flow is added for only `validator-primary` and `follower` pods. These pods will first restart all the other (statefulset) pods in the namespace with a 5 minute gaps (so that at most one validator node is restarted) and will finally restart itself.
> Periodically restart pods

- bases/shared/instagoric-server/server.js
The PR revises the `<a>` tag content for clarity. Previously, the link text suggested a dashboard destination, but the `href` actually directed users to the logs, creating confusion.
> chore: update logs link text to 'Click Here' for clarity

- bases/shared/instagoric-server/package.json
- bases/shared/instagoric-server/yarn.lock
This PR adds `nodemon` as a development dependency. It automatically restarts the server whenever code changes, improving the development workflow with hot reloading. Currently, `yarn start` runs the server using `node`, but switching to `nodemon` will eliminate the need for manual restarts during development.
> feat: use nodemon to start dev server for hot reloading

- bases/shared/instagoric-server/server.js
This PR addresses an issue where the server fails to start if `git-revision.txt` is missing. By wrapping the file reading code in a try-catch block, we can ensure the server starts by assigning a fallback value to the revision if the file is absent.
> chore: ensure server starts by handling git-revision.txt read failures

- bases/shared/instagoric-server/server.js
During development on #69, I encountered an issue where ATOM's A3P denom was not visibly selectable via the 'Custom Denom' button on the A3P wallet interface. 
Initially, the token seemed missing from the options, leading me to hardcode the denom for testing purposes. However, I later discovered that the denomination was indeed present but not immediately visible due to the absence of a scroll effect on the UI. 
This PR introduces CSS improvements to enhance the visibility of the scrollbar, making it evident that multiple denomination options are available for selection. 
https://github.com/user-attachments/assets/a70a564f-2940-4114-8ceb-d00e8182ad86
> chore: css changes to make scrollbar/scrolling evident on screen

- bases/shared/instagoric-server/README.md
Adding the role of `FAUCET_KEYNAME` environment variable and how to use the `validator` wallet for provisioning with A3P.
> docs: working with a3p

- bases/node/node.yaml
Removed `log-otel` container which was only contributing towards the log quota consumption and doesn't really add any value right now
Think of a way of getting alerts on unexpected otel errors
> Remove log-otel container

- bases/node/node.yaml
The refactor of entrypoint script zips all the scripts before uploading due to which the `envsubst` in `init.sh` couldn't replace `CLUSTER_NAME` usage in the scripts. This PR adds the `CLUSTER_NAME` as env var in `node` yaml
> Fix missing CLUSTER NAME

- bases/shared/scripts/main.sh
Old contextual slog files were not uploaded when a node restarted due to incorrect formatting through `awk`. This PR fixes that.
> Fix regex to include contextual slog file when uploading old logs

- bases/shared/scripts/logs-cleanup.sh
- bases/shared/scripts/main.sh
This PR is a part of entrypoint refactoring effort and separate logs cleanup script
> chore: Separate logs backup script

- bases/shared/scripts/main.sh
In this [PR](https://github.com/Agoric/instagoric/pull/90), we accidentaly moved instagoric server run below `get_ips` blocking call so seed node never starts the chain
> fix: Run instagoric server before getting ips

- bases/explorer/config.patch
- bases/explorer/entrypoint.sh
- bases/explorer/explorer.yaml
This PR fixes a regression of https://github.com/Agoric/instagoric/pull/96
When connecting the wallet with chain, the generated chain info has `/api` and `/rpc` urls instead of the actual rpc and api urls. This PR adds a patch to use the appropriate urls for the chain info
Verify that suggesting chain from https://emerynet.explorer.agoric.net/wallet/suggest will not work but https://usman.explorer.agoric.net/wallet/suggest should
> fix(Explorer): Incorrect rpc/api url in chain info for Keplr wallet connection

- bases/explorer/config.patch
The IBC path of explorer doesn't respect the connection ID in the URL. So even if we visit `/[chain-name]/ibc/connection/connection-1`, it will redirect to `/[chain-name]/ibc/connection/connection-0` so the url is not shareable. This PR fixes that issue using a patch.
For verification, https://devnet.explorer.agoric.net/agoric/ibc/connection/connection-1 will redirect automatically to https://devnet.explorer.agoric.net/agoric/ibc/connection/connection-0 whereas https://muneeb.explorer.agoric.net/agoric/ibc/connection/connection-1 will not
> fix: Explorer IBC path doesn't respect connection ID in url
